IEP projekat/IEP projekat/Models/Auction.cs
namespace IEP_projekat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Auction")]
    public partial class Auction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auction()
        {
            Bids = new HashSet<Bid>();
        }

        [Key]
        public int IdAuction { get; set; }

        public int IdUser { get; set; }

        [Required]
        public string Product { get; set; }

        public long Time { get; set; }

        public int BeginningPrice { get; set; }

        public int EndPrice { get; set; }

        public DateTime CreateTime { get; set; }

        public DateTime StartTime { get; set; }

        public DateTime EndTime { get; set; }

        [Required]
        [StringLength(20)]
        public string State { get; set; }

        [Column(TypeName = "image")]
        [Required]
        public byte[] Image { get; set; }

        public Guid IdAuctionGUID { get; set; }

        public virtual Account Account { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
    }
}

IEP projekat/IEP projekat/Controllers/TokenOrderController.cs
using IEP_projekat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IEP_projekat.Models;
using System.Data.Entity;
using IEP_projekat.Models.Extended;
using System.Data;
using PagedList;
using IEP_projekat.Authorization_filters;
using System.Net.Mail;
using System.Text;
using log4net;

namespace IEP_projekat.Controllers
{
    public class TokenOrderController : Controller
    {
        private IEPBaza myDB = new IEPBaza();
        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private const string CENTILI_SUCCESS = "success";
        private const string CENTILI_FAIL = "fail";

        [UserAuthorized]
        public ActionResult Index(int? page)
        {
            Account currentUser = Session["User"] as Account;
            if (currentUser != null)
            {
                //Ibacuju se sve narudzbine po opadajucem redosledu datuma
                var tokenOrders = myDB.TokenOrders.Where(t => t.IdUser == currentUser.IdUser).OrderByDescending(t=>t.TimeSubmitted).ToList();

                AdminInfo adminInfo = myDB.AdminInfoes.FirstOrDefault();
                int items = adminInfo.ItemsPage;

                int pageNumber = (page ?? 1);
                return View(tokenOrders.ToPagedList(pageNumber, items));
            }

            log.Info("TokenOrder/Index No logged in user");
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [UserAuthorized]
        public ActionResult Details(int? id)
        {
            if (id.HasValue)
            {
                TokenOrder myTokenOrder = myDB.TokenOrders.Find(id);
                if (myTokenOrder != null)
                {
                    return View(myTokenOrder);
                }

                return HttpNotFound();
            }

            log.Info("TokenOrder/Details No argumetn for method");
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [UserAuthorized]
        public ActionResult Create()
        {
            AdminInfo adminInfo = myDB.AdminInfoes.FirstOrDefault();
            Session["silver"] = adminInfo.SilverPack;
            Session["gold"] = adminInfo.GoldPack;
            Session["platinum"] = adminInfo.PlatinumPack;
            Session["price"] = (int)adminInfo.TokenValue;
            Session["currency"] = (String)adminInfo.Currency;
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [CurrentUserAuthorized]
        public ActionResult Create(int id, string pack)
        {
            Account currentUser = Session["User"] as Account;
            Account myUser = myDB.Accounts.Find(id);
            AdminInfo adminInfo = myDB.AdminInfoes.FirstOrDefault();

            Session["silver"] = adminInfo.SilverPack;
            Session["gold"] = adminInfo.GoldPack;
            Session["platinum"] = adminInfo.PlatinumPack;
            Session["price"] = (int)adminInfo.TokenValue;
            Session["currency"] = (String)adminInfo.Currency;

            if (currentUser != null && adminInfo != null && currentUser.IdUser == myUser.IdUser)
            {
                int numberOfTokens = 0;
                double newPrice = 0;
                switch (pack)
                {
                    case "silver":
                        numberOfTokens = adminInfo.SilverPack;
                        //popust od 5%
                        newPrice = numberOfTokens * adminInfo.TokenValue * 0.95;
                        break;
                    case "gold":
                        numberOfTokens = adminInfo.GoldPack;
                        //popust od 10%
                        newPrice = numberOfTokens * adminInfo.TokenValue * 0.90;
                        break;
                    case "platinum":
                        numberOfTokens = adminInfo.PlatinumPack;
                        //popust od 15%
                        newPrice = numberOfTokens * adminInfo.TokenValue * 0.85;
                        break;
                }

                TokenOrder newTokenOrder = new TokenOrder
                {
                    IdUser = myUser.IdUser,
                    NumOfTokens = numberOfTokens,
                    Price = (int)newPrice,
                    State = "SUBMITED",
                    TimeSubmitted = System.DateTime.Now,
                    IdOrderGUID = Guid.NewGuid()
            };

                myDB.TokenOrders.Add(newTokenOrder);
                myDB.SaveChanges();

                return Redirect("http://stage.centili.com/payment/widget?apikey=5e312449d51251970f17be58787d70cf&country=rs&reference=" + newTokenOrder.IdOrderGUID);
            }

            return View();
        }
        
        public ActionResult PaymentCompleted(Guid reference, string status)
        {
            using (var trans = myDB.Database.BeginTransaction(IsolationLevel.Serializable))
            {
                TokenOrder tokenOrder = myDB.TokenOrders.Where(t => t.IdOrderGUID == reference).FirstOrDefault();
                Account myUser = myDB.Accounts.Where(a => a.IdUser == tokenOrder.IdUser).FirstOrDefault();
                Account currentUser = Session["User"] as Account;

                if (tokenOrder != null && currentUser != null && currentUser.IdUser == myUser.IdUser)
                {
                    try
                    {
                        if (status == CENTILI_SUCCESS)
                        {
                            tokenOrder.State = "COMPLETED";
                            myUser.Tokens += tokenOrder.NumOfTokens;
                            Session["User"] = myUser;
                            SendEmailToBuyerSuccess(myUser, tokenOrder);
                        }
                        else
                        {
                            tokenOrder.State = "CANCELED";
                            SendEmailToBuyerFail(myUser, tokenOrder);
                        }

                        myDB.Entry(myUser).State = EntityState.Modified;
                        myDB.SaveChanges();
                        myDB.Entry(tokenOrder).State = EntityState.Modified;
                        myDB.SaveChanges();
                        trans.Commit();
                    }
                    catch (Exception e)
                    {
                        log.Info("TokenOrder/PaymentCompleted Exception with Centili payment");
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                }

                return RedirectToAction("Details", "User", new { id = myUser.IdUser });
            }
        }

        [NonAction]
        public void SendEmailToBuyerSuccess(Account reciver, TokenOrder myTokenOrder)
        {
            string emailSubject = "Payment successful!";
            string emailBody = "Dear " + reciver.FirstName + " " + reciver.LastName + ", <br/>" +
                                "Your payment was successful! You bought " + myTokenOrder.NumOfTokens + " tokens. Use them wisely!<br /> " +
                                "Sincerely, <br/>" +
                                "Auction mania";
            bool status = SendEmail(reciver, emailSubject, emailBody);
        }

        [NonAction]
        public void SendEmailToBuyerFail(Account reciver, TokenOrder myTokenOrder)
        {
            string emailSubject = "Payment UNsuccessful!";
            string emailBody = "Dear " + reciver.FirstName + " " + reciver.LastName + ", <br/>" +
                                "Your payment was unsuccessful! Please try again later. We are sorry for the inconvinience. <br /> " +
                                "Sincerely, <br/>" +
                                "Auction mania";
            bool status = SendEmail(reciver, emailSubject, emailBody);
        }

        [NonAction]
        public bool SendEmail(Account reciver, string subject, string emailBody)
        {
            try
            {
                string senderEmail = System.Configuration.ConfigurationManager.AppSettings["SenderEmail"].ToString();
                string senderPassword = System.Configuration.ConfigurationManager.AppSettings["SenderPassword"].ToString();

                SmtpClient client = new SmtpClient("smtp.gmail.com", 587);
                client.EnableSsl = true;
                client.Timeout = 100000;
                client.DeliveryMethod = SmtpDeliveryMethod.Network;
                client.UseDefaultCredentials = false;
                client.Credentials = new NetworkCredential(senderEmail, senderPassword);

                MailMessage mailMessage = new MailMessage(senderEmail, reciver.Email, subject, emailBody);
                mailMessage.IsBodyHtml = true;
                mailMessage.BodyEncoding = UTF8Encoding.UTF8;

                client.Send(mailMessage);

                return true;
            }
            catch (Exception ex)
            {
                log.Info("TokenOrder/SendEmail Error with mail sending");
                return false;
            }
        }

        [NonAction]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                myDB.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IEP projekat/IEP projekat/Views/Auction/CreateAuction.cshtml
@model IEP_projekat.Models.Extended.AuctionCreateExtended

@{
    ViewBag.Title = "CreateAuction";
    Layout = "~/Views/Shared/_Layout.cshtml";

    int priceOfToken = (int)Session["price"];
    String myCurrency = (String)Session["currency"];
}

<div class="container">

    <div class="row">
        <div class="col-md-12">
            <center>
                <h2>CreateAuction</h2>
                <hr />
                <p>
                    Create your own auction and make money. After you submit your bid, we have to wait for the
                    admin to approve your auction before we start. You have to put the value of your item in tokens. 
                </p>
                <p>
                    <strong>Reminder:</strong>
                    Value of one token is @priceOfToken @myCurrency
                </p>
                <hr />
            </center>
        </div>
    </div>

    <div class="row">
        @using (Html.BeginForm("CreateAuction", "Auction", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Product, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Product, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Product, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="ImageFile" required />
                        @Html.ValidationMessageFor(model => model.ImagePath)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StartingPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.StartingPrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StartingPrice, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default btn-lg" style="margin-right:10px" />
                        @Html.ActionLink("Cancle", "Index", "Auction", null, new { @class = "btn btn-info" })
                    </div>
                </div>
            </div>
        }
    </div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IEP projekat/IEP projekat/Views/Auction/Index.cshtml
@model PagedList.IPagedList<IEP_projekat.Models.Auction>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "All auctions";
    Layout = "~/Views/Shared/_Layout.cshtml";

    IEP_projekat.Models.Account currentUser = Session["User"] as IEP_projekat.Models.Account;
    int idCurrentUser = -1;
    if (currentUser != null)
    {
        idCurrentUser = currentUser.IdUser;
    }
}

<div class="container">
    <div class="row" id="notify">
    </div>

    @if (currentUser == null)
    {
        <div class="row">
            <br />
            <div class="alert alert-warning">
                <strong>You are not logged-in!</strong> If you want to join the fun please @Html.ActionLink("login", "Login", "User") or @Html.ActionLink("register", "Register", "User")
            </div>
        </div>
    }

    @if ((string)TempData["message"] != null)
    {
        <div class="row">
            <br />
            <div class="alert alert-warning" role="alert">
                <strong>@TempData["message"].ToString()</strong>
            </div>
        </div>
    }


    <div class="row">
        <div class="col-md-12">
            <center>
                <h2>
                    Let the bidding war begin!
                </h2>
                <hr />
                <p>
                    Here, only the fastest bidders can prevail. If you wish to win, you
                    better be on your A game. We want a clean game, so here are the rules:
                </p>
                <p>
                    Every auction has a time limit for taking bids. You can raise the current price for 1 token (by default).
                    Time waits for no man, so be quick.
                </p>
                <p><strong>May the best bidders win!</strong></p>
            </center>
        </div>
    </div>

    <hr />

    <div class="container">
        <button type="button" class="btn btn-light btn-lg" data-toggle="collapse" data-target="#demo">Filter by:</button>
        @if (currentUser != null)
        {
            <a href=@Url.Action("Create", "TokenOrder") class="btn btn-lg btn-danger pull-right" role="button">Buy tokens!</a>
            <a href=@Url.Action("CreateAuction","Auction") class="btn btn-lg btn-warning pull-right" style="margin-right:15px" role="button">Create auction</a>
        }
        <div id="demo" class="collapse">
            @using (Html.BeginForm("Index", "Auction", FormMethod.Get))
            {
                <div class="row">
                    <div class="col-md-4">
                        <h5>
                            Search:
                        </h5>
                        @Html.TextBox("SearchString", null, new { @class = "form-control", @placeholder = "Search by name" })
                    </div>
                    <div class="col-md-2">
                        <h5>
                            Minimum price:
                        </h5>
                        @Html.TextBox("MinValue", null, new { @class = "form-control", @placeholder = "Min price" })
                    </div>
                    <div class="col-md-2">
                        <h5>
                            Maximum price:
                        </h5>
                        @Html.TextBox("MaxValue", null, new { @class = "form-control", @placeholder = "Max price" })
                    </div>
                    <div class="col-md-2">
                        <h5>
                            Items displayed:
                        </h5>
                        @Html.TextBox("ItemsPerPage", null, new { @class = "form-control", @placeholder = "Items on page" })
                    </div>
                    <br />
                    <div class="col-md-2">
                        <input type="submit" value="Search" class="btn btn-primary text-strong" />
                        <a href="@Url.Action("Index")" class="btn btn-secondary" role="button">Reset</a>
                    </div>
                </div>
            }
        </div>
    </div>

    <br />
    <div class="row" id="appending">
        @foreach (var item in Model)
        {
            string imreBase64Data = Convert.ToBase64String(item.Image);
            string imgDataUrl = string.Format("data:image/png;base64,{0}", imreBase64Data);
            <div>
                <div class="col-md-3">
                    <div class="card" style="height: 20%; max-height:20%;  margin: 2px; padding:2px; border: 2px solid #e5e5e5; border-radius: 16px">
                        <img class="card-img-top" src="@imgDataUrl" alt="Card image cap" style="width: 100%; height:200px; object-fit: contain;" />
                        <div class="card-body text-center">
                            <hr />
                            <h3 class="card-title" style="height:50px; max-height:50px">
                                @Html.ActionLink(item.Product, "Details", "Auction", new { id = item.IdAuction }, null)
                            </h3>
                            <dl class="card-text">
                                <dt>Price (in tokens)</dt>
                                <dd id="@item.IdAuction price">@item.EndPrice</dd>

                                <dt>Time left</dt>
                                <dd id="@item.IdAuction timeLeft"></dd>

                                <dt>Winning bidder</dt>
                                <dd id="@item.IdAuction bidder">
                                    @if (item.Bids.Where(b => b.IdAuction == item.IdAuction).OrderByDescending(b => b.Tokens).FirstOrDefault() != null)
                                    {
                                        @item.Bids.Where(b => b.IdAuction == @item.IdAuction).OrderByDescending(b => b.Tokens).FirstOrDefault().Account.Email.ToString();

                                    }
                                    else
                                    {
                                        if (!item.State.Contains("COMPLETED"))
                                        {
                                            <p>Be the first one!</p>
                                        }
                                        else
                                        {
                                            <p>Noone placed a bid! :(</p>
                                        }

                                    }
                                </dd>
                            </dl>
                            <hr />
                            <a id="@item.IdAuction button" href=@Url.Action("MakeBid",new { curAuction = item.IdAuction}) class="btn btn-danger btn-lg" role="button" style="margin-bottom:5px">
                                Bid!
                            </a>
                        </div>
                    </div>
                </div>

                @if (!item.State.Contains("COMPLETED"))
                {
                    <script>
                        var countDownDate@(item.IdAuction) = new Date().getTime() - Math.floor(@System.DateTime.Now.Subtract(@item.StartTime).TotalMilliseconds) + @item.Time * 1000;
                        var x = setInterval(function() {

                            var targetField = @item.IdAuction + " timeLeft";
                            var now = new Date().getTime();
                            var distance = countDownDate@(item.IdAuction) - now;

                            if (distance <= 0) {
                                clearInterval(x);

                                $.ajax({
                                    type: "POST",
                                    url: '@Url.Action("CompleteAuction", "Auction", new { id = item.IdAuction})',
                                    dataType: "json",
                                    contentType: "application/json; charset=utf-8",
                                    success: function () {
                                        alert("Prosao");
                                    }
                                });

                                document.getElementById(targetField).innerHTML = "<mark> COMPLETED </mark>";
                                targetField = @item.IdAuction + " button";
                                document.getElementById(targetField).setAttribute("disabled", "true");

                                return;
                            }

                            var days = Math.floor(distance / (1000 * 60 * 60 * 24));
                            var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                            var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
                            var seconds = Math.floor((distance % (1000 * 60)) / 1000);

                            document.getElementById(targetField).innerHTML = days + "d " + hours + "h "
                                + minutes + "m " + seconds + "s ";

                        }, 1000);

                    </script>
                }
                else
                {
                    <script>
                        var targetField = @item.IdAuction + " timeLeft";
                        document.getElementById(targetField).innerHTML = "<mark> COMPLETED </mark>";
                        targetField = @item.IdAuction + " button";
                        document.getElementById(targetField).setAttribute("disabled", "true");
                    </script>
                }
            </div>
        }
    </div>

    <div class="row">
        <br />

        <center>
            @Html.PagedListPager(Model, page => Url.Action("Index",
                new { page, searchString = ViewBag.CurrentFilter, MinValue = ViewBag.MinValue, MaxValue = ViewBag.MaxValue, ItemsPerPage = ViewBag.ItemsPerPage }))
        </center>
    </div>
</div>

@section scripts 
    {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.3.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
        $(function () {
            // Reference the auto-generated proxy for the hub.
            var auctions = $.connection.bidding;
            // Create a function that the hub can call back to display messages.
            auctions.client.UpdateAuction = function (idAuction, newPrice, leadingBidder)
            {
                var targetField = idAuction + " price";
                document.getElementById(targetField).innerHTML = newPrice;
                targetField = idAuction + " bidder";
                document.getElementById(targetField).innerHTML = leadingBidder;
            };

            auctions.client.ReturnTokens = function (previousBidder, numberOfTokens)
            {
                if (@idCurrentUser == previousBidder)
                {
                    var targetField ="myTokens";
                    document.getElementById(targetField).innerHTML = numberOfTokens;
                }
            };

            auctions.client.ReturnTokensNotifications = function (previousBidder, textNotification)
            {
                if (@idCurrentUser == previousBidder)
                {
                    var myNotification = "<br /><div class='col-md-12'><div class='alert alert-danger' role='alert'> " + 
                                            "<strong> " + textNotification + "</strong></div></div>";
                    var targetField = "notify";
                    var x = document.getElementById(targetField).innerHTML;
                    document.getElementById(targetField).innerHTML = myNotification + x;
                }
            };

            auctions.client.NewAuction = function (textNotification)
            {
                var myNotification = "<br /><div class='col-md-12'><div class='alert alert-info' role='alert'> " + 
                                            "<strong> " + textNotification + "</strong></div></div>";
                var targetField = "notify";
                var x = document.getElementById(targetField).innerHTML;
                document.getElementById(targetField).innerHTML = myNotification + x;
            };

            $.connection.hub.start().done(function () {
            });
        });
    </script>
    }